'use strict';
const state = {token: '', status: null, page: 'overview', results: {}, jobs: {}, drafts: {}, busy: false, searchType: 'search-knowledge', traceType: 'trace'};
const pages = {overview: '概览', analysis: '需求分析', search: '知识与代码', trace: '调用链与影响', conflicts: '契约与冲突', repositories: '仓库与索引'};
const actionNames = {'search-knowledge':'知识检索','search-interface':'接口定位','search-code':'代码检索',trace:'调用链追踪',impact:'影响分析','detect-conflicts':'冲突检测','analyze-requirement':'需求分析',snapshots:'快照检查','index-code':'代码索引','index-docs':'知识索引'};
const actionPage = action => action.startsWith('search-') ? 'search' : ({trace:'trace',impact:'trace','detect-conflicts':'conflicts','analyze-requirement':'analysis'})[action] || 'repositories';
const $ = id => document.getElementById(id);
function el(tag, cls='', text='') { const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text; return n; }
function add(parent, ...children){children.flat().filter(Boolean).forEach(c=>parent.append(c));return parent;}
function button(text, cls, fn){const b=el('button',cls,text);b.type='button';b.addEventListener('click',fn);return b;}
function badge(text,kind=''){return el('span','badge '+kind,text);}
function heading(eyebrow,title,subtitle){return add(el('div','heading'),add(el('div'),el('span','eyebrow',eyebrow),el('h1','',title),el('p','',subtitle)),badge('LOCAL WORKSPACE'));}
function panel(title,subtitle){const box=el('section','panel');add(box,add(el('div','panel-header'),el('h2','',title),el('span','subtle',subtitle||'')));const body=el('div','panel-body');add(box,body);return {box,body};}
function empty(title,text,symbol='⌕'){return add(el('div','empty'),el('div','empty-symbol',symbol),el('h3','',title),el('p','',text));}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),6500);}
async function api(path,options={}){const response=await fetch('/api/'+path,{...options,headers:{'Content-Type':'application/json','X-BankDev-Token':state.token,...options.headers}});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
async function refresh(){state.status=await api('status');$('connection-label').textContent='本地已连接';}
function go(page){
  if(page==='trace'&&state.pendingTrace){
    state.drafts.trace={query:state.pendingTrace,type:'trace',direction:'downstream',max_depth:'8'};
    state.traceType='trace';
  }
  if(location.hash==='#'+page)render();else location.hash=page;
}
function field(label,name,value='',type='input',placeholder=''){const wrap=el('label','field');add(wrap,el('span','',label));const input=el(type);input.name=name;input.value=value;input.placeholder=placeholder;add(wrap,input);return {wrap,input};}
function selectField(label,name,options,value){const {wrap,input}=field(label,name,'','select');for(const [v,t] of options){const option=el('option','',t);option.value=v;add(input,option);}input.value=value||options[0][0];return {wrap,input};}
function rawDetails(data){const d=el('details');add(d,el('summary','','查看结构化结果'),el('pre','raw-json',JSON.stringify(data,null,2)));return d;}
function downloads(job){const row=el('div','button-row');add(row,button('↓ JSON','secondary',()=>download(job,'json')));if(job.action==='analyze-requirement')add(row,button('↓ Markdown','secondary',()=>download(job,'markdown')));return row;}
async function download(job,format){try{const r=await fetch(`/api/export/${job.id}?format=${format}`,{headers:{'X-BankDev-Token':state.token}});if(!r.ok)throw new Error((await r.json()).error);const url=URL.createObjectURL(await r.blob());const a=el('a');a.href=url;a.download=`bankdev-${job.action}-${job.id.slice(0,6)}.${format==='json'?'json':'md'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast(e.message);}}
async function run(action,args={}){
  if(state.busy)return toast('当前任务尚未完成，请稍后再试。');
  state.busy=true;const bar=$('taskbar');bar.replaceChildren(el('span','spinner'),el('span','',`${actionNames[action]}进行中… 可继续浏览其他页面`));bar.classList.remove('hidden');
  try{const submitted=await api('jobs',{method:'POST',body:JSON.stringify({action,arguments:args})});let job;
    do{await new Promise(resolve=>setTimeout(resolve,650));job=await api('jobs/'+submitted.id);}while(['queued','running'].includes(job.status));
    if(job.status==='failed')throw new Error(job.error);
    const page=actionPage(action);state.results[page]=job;state.jobs[job.id]=job;
    await refresh();if(state.page===page||state.page==='overview')render();else toast(`${actionNames[action]}已完成，可在对应页面查看结果。`);
  }catch(e){toast(e.message);}finally{state.busy=false;bar.classList.add('hidden');}
}
function repositoryTable(){const table=el('table','repo-table');add(table,add(el('thead'),add(el('tr'),['仓库','固定版本','索引文件','状态'].map(v=>el('th','',v)))));const tbody=el('tbody');for(const r of state.status.repositories){const indexed=state.status.indexed.find(v=>v.repo_id===r.id&&v.commit_sha===r.commit);const knowledge=r.kind==='git_markdown';const count=knowledge?state.status.counts.documents:indexed?.file_count;const tr=el('tr');add(tr,add(el('td'),add(el('div','repo-name'),el('span','repo-symbol',r.id==='bank_knowledge'?'KB':r.id.slice(0,1).toUpperCase()),el('span','',r.id==='bank_knowledge'?'Bank Knowledge':r.id.toUpperCase()))),add(el('td'),el('code','',r.commit.slice(0,8))),el('td','',count==null?'—':count.toLocaleString()),add(el('td'),badge(count?'已建索引':'待建索引',count?'good':'')));add(tbody,tr);}add(table,tbody);return add(el('div','table-wrap'),table);}
function pipeline(){return add(el('div','pipeline'),['理解需求','查找证据','追踪代码','核验结论'].map((s,i)=>add(el('div','pipeline-step'),el('b','',String(i+1)),el('span','',s))));}
function renderOverview(){const main=$('main'),s=state.status;add(main,heading('DEVELOPMENT INTELLIGENCE','研发分析，从证据开始','连接业务知识与真实代码，在一个工作台里完成检索、追踪和需求分析。'));
  const stats=el('div','stats');const metrics=[['已登记仓库',s.repositories.length,'个','覆盖业务系统与私有知识库','▤'],['代码符号',s.counts.symbols,'','固定源码快照 · 静态索引','⑂'],['接口入口',s.counts.endpoints,'','OpenAPI 与代码入口','⇄'],['知识文档',s.counts.documents,'篇',`${s.counts.document_chunks} 个可检索知识块`,'▧']];for(const [label,value,unit,caption,icon] of metrics)add(stats,add(el('div','stat'),add(el('div','stat-top'),el('span','',label),el('span','stat-icon',icon)),add(el('div','stat-value','',),document.createTextNode(value.toLocaleString()),el('small','',unit)),el('div','stat-caption',caption)));add(main,stats);
  const columns=el('div','columns'),quick=panel('开始一次需求分析','从业务问题到证据报告');const goal=field('你想了解什么？','quickGoal','','textarea','例如：分析 01100121 贷款产品查询的当前契约、调用链和影响范围');goal.input.className='quick-area';add(quick.body,goal.wrap);const chips=el('div','chips');for(const value of ['01100121 贷款产品查询','定位接口与当前契约','查看跨仓库调用关系'])add(chips,button(value,'chip',()=>{goal.input.value=value;}));add(quick.body,chips,pipeline());add(quick.box,add(el('div','panel-foot'),el('span','subtle','先明确目标与范围，再运行分析。'),button('进入需求分析  ↗','primary',()=>{state.pendingGoal=goal.input.value;if(state.drafts.analysis)state.drafts.analysis.goal=goal.input.value;go('analysis');})));
  const guide=panel('每条事实，都有出处','EVIDENCE FIRST');for(const [icon,title,desc] of [['01','知识与代码分别呈现','区分当前代码、知识记载与历史事实'],['02','从入口追踪真实关系','展示静态调用、Mapper 与表依赖'],['03','证据门禁先于结论','保留冲突、覆盖缺口和待确认问题']])add(guide.body,add(el('div','list-row'),el('span','row-icon',icon),add(el('div','row-text'),el('strong','',title),el('small','',desc))));add(guide.body,add(el('div','callout'),el('strong','','模型辅助，可选开启'),document.createTextNode('默认使用确定性模板。模型提出建议，已确认事实由证据核验。')));add(columns,quick.box,guide.box);add(main,columns);
  const repositories=panel('已连接的分析范围','版本来自当前配置');repositories.body.remove();add(repositories.box,repositoryTable(),add(el('div','panel-foot'),el('span','subtle','索引在本机保存，业务仓库保持只读。'),button('管理仓库与索引 →','ghost',()=>go('repositories'))));add(main,el('div','section-space'),repositories.box);
  if(s.error)add(main,el('div','notice',s.error));if(!s.index_exists)add(main,el('div','notice','索引尚未建立，请在“仓库与索引”中先更新代码索引和知识索引。'));
  if(s.jobs.length){const recent=panel('最近任务','仅保留当前服务会话的 20 个任务');for(const job of s.jobs.slice(0,5)){const row=add(el('div','list-row'),el('span','row-icon','↗'),add(el('div','row-text'),el('strong','',actionNames[job.action]),el('small','',job.id.slice(0,8))),badge(({completed:'已完成',failed:'失败',running:'执行中',queued:'排队中'})[job.status],job.status==='completed'?'good':''));if(job.status==='completed')add(row,button('查看','ghost',async()=>{try{const loaded=await api('jobs/'+job.id);state.results[actionPage(loaded.action)]=loaded;go(actionPage(loaded.action));}catch(e){toast(e.message);}}));add(recent.body,row);}add(main,recent.box);}}
function evidenceButton(reference){if(!reference?.web_evidence_id)return null;return button(`↗ ${reference.path?.split('/').pop()||'查看证据'}${reference.start_line?':'+reference.start_line:''}`,'evidence-button',()=>showEvidence(reference.web_evidence_id));}
async function showEvidence(id){const dialog=$('evidence-dialog');$('evidence-content').replaceChildren(el('p','subtle','正在读取证据…'));if(!dialog.open)dialog.showModal();try{const data=await api('evidence/'+id);const body=$('evidence-content');body.replaceChildren(add(el('div','source-meta'),el('div','',`${data.repo_id} / ${data.path}`),el('code','',`snapshot: ${data.snapshot}`)));const source=el('div','source');data.lines.forEach((text,i)=>{const line=data.display_start+i;add(source,add(el('div','source-line'+(line>=data.start_line&&line<=data.end_line?' highlight':'')),el('span','line-number',String(line)),el('span','source-code',text)));});add(body,source);if(data.truncated)add(body,el('p','hint','证据范围较长，本次最多预览 200 行。'));}catch(e){$('evidence-content').replaceChildren(el('p','error-state',e.message));}}
function renderSearch(){const main=$('main');add(main,heading('SEARCH & DISCOVERY','知识与代码','按业务术语、接口号或代码符号检索，并直接查看对应证据。'));const tabs=el('div','tabs');for(const [value,label] of [['search-knowledge','知识文档'],['search-interface','接口定位'],['search-code','代码符号']])add(tabs,button(label,'tab'+(state.searchType===value?' active':''),()=>{state.searchType=value;render();}));add(main,tabs);const form=el('form','search-box'),input=el('input');input.name='query';input.setAttribute('aria-label','检索关键词');input.placeholder=state.searchType==='search-code'?'类名、方法名、operationId…':'输入接口号或业务关键词，如 01100121、贷款产品';input.required=true;const submit=el('button','primary','检索  →');add(form,input,submit);form.addEventListener('submit',e=>{e.preventDefault();run(state.searchType,{query:input.value});});add(main,form);const chips=el('div','chips');for(const term of ['01100121','贷款产品','FineractPersonalLoanClient'])add(chips,button(term,'chip',()=>{input.value=term;run(state.searchType,{query:term});}));add(main,chips);const job=state.results.search;if(!job||job.action!==state.searchType)return add(main,empty('查找你需要的依据','选择一种检索方式。结果将保留所属仓库、版本与可预览的证据位置。'));const data=job.result;add(main,add(el('div','heading'),el('div','count',`“${data.query}” · 返回 ${data.count} 条结果`),downloads(job)));const results=data.results||data.matches||[];if(!results.length)return add(main,empty('本次范围内未找到匹配项','请尝试接口号、较短术语或完整代码符号；未命中不代表其他版本或未扫描路径中不存在。'));const box=el('div','panel');for(const item of results){const r=el('article','result');add(r,add(el('div','result-title'),badge(item.repo_id==='bank_knowledge'?'知识':(item.repo_id||'代码').toUpperCase()),el('span','',item.title||item.label||`${item.http_method} ${item.route}`)));if(item.excerpt)add(r,el('p','',item.excerpt));if(item.operation_id)add(r,el('p','mono',item.operation_id));add(r,add(el('div','result-meta'),el('span','',item.heading_path||item.kind||item.status||''),evidenceButton(item.evidence)));if(item.endpoint_id)add(r,button('追踪调用链 →','ghost',()=>{state.pendingTrace=item.endpoint_id;go('trace');run('trace',{query:item.endpoint_id});}));add(box,r);}add(main,box);}
function renderTrace(){const main=$('main');add(main,heading('CODE RELATIONSHIPS','调用链与影响','从一个入口出发，查看上下游静态关系与潜在变更影响。'));const form=el('form','panel panel-body controls');const input=field('分析起点','query',state.pendingTrace||'01100121','input','接口号、operationId 或符号');state.pendingTrace=null;input.wrap.classList.add('wide');const type=selectField('分析方式','type',[['trace','调用链追踪'],['impact','影响候选']],state.traceType);const direction=selectField('追踪方向','direction',[['downstream','下游'],['upstream','上游'],['both','双向']]);const depth=field('最大深度','max_depth','8');depth.input.type='number';depth.input.min=0;depth.input.max=32;const submit=el('button','primary','开始追踪');add(form,input.wrap,type.wrap,direction.wrap,depth.wrap,submit);form.addEventListener('submit',e=>{e.preventDefault();state.traceType=type.input.value;run(type.input.value,{query:input.input.value,direction:direction.input.value,max_depth:Number(depth.input.value)});});add(main,form);const job=state.results.trace;if(!job)return add(main,el('div','section-space'),empty('让调用关系清晰可见','输入 01100121 查看本地查询链，也可输入 operationId 或符号探索跨仓库静态关系。','⑂'));const data=job.result;add(main,add(el('div','heading section-space'),el('div','count',`分析起点：${data.start}`),downloads(job)));if(data.coverage?.truncated)add(main,el('div','notice','已达到本次深度或节点预算，展示的是部分调用关系。'));if(job.action==='trace'){const p=panel('静态调用关系',`${data.nodes.length} 个节点 · ${data.edges.length} 条关系`);p.body.remove();add(p.box,graph(data),el('div','graph-summary','点击节点查看证据。连线来自静态索引，不代表运行时调用。'));add(main,p.box);const details=panel('节点与出处','完整节点列表');for(const n of data.nodes)add(details.body,add(el('div','list-row'),badge(n.repo_id.toUpperCase()),add(el('div','row-text'),el('strong','',n.label),el('small','',n.kind)),evidenceButton(n.evidence)));add(main,details.box);}else{for(const [key,label] of [['direct_impacts','直接依赖候选'],['transitive_candidates','传递影响候选']]){const p=panel(label,`${data[key].length} 项`);if(!data[key].length)add(p.body,el('p','subtle','本次静态图和预算内未找到此类影响项。'));for(const n of data[key])add(p.body,add(el('div','list-row'),badge(n.repo_id),add(el('div','row-text'),el('strong','',n.label),el('small','',`距离 ${n.distance}`)),evidenceButton(n.evidence)));add(main,p.box);}add(main,el('div','notice',data.warning));}if(data.unresolved?.length){const p=panel('未解析关系',`${data.unresolved.length} 项`);for(const n of data.unresolved)add(p.body,add(el('div','fact'),el('p','',`${n.expression} · ${n.reason}`),evidenceButton(n.evidence)));add(main,p.box);}}
function graph(data){const wrap=el('div','graph-wrap');const ns='http://www.w3.org/2000/svg';const svg=(tag,attrs={})=>{const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;};const roots=new Set(data.roots),distance=new Map(data.roots.map(v=>[v,0]));for(let round=0;round<8;round++)for(const edge of data.edges){const pairs=data.direction==='upstream'?[[edge.target,edge.source]]:data.direction==='both'?[[edge.source,edge.target],[edge.target,edge.source]]:[[edge.source,edge.target]];for(const[a,b]of pairs)if(distance.has(a)&&!distance.has(b))distance.set(b,Math.min(6,distance.get(a)+1));}const nodes=[...data.nodes].sort((a,b)=>(distance.get(a.id)||0)-(distance.get(b.id)||0)).slice(0,60),pos=new Map(),rows={};for(const node of nodes){const depth=distance.get(node.id)??0;const row=rows[depth]||0;rows[depth]=row+1;pos.set(node.id,{x:20+depth*245,y:25+row*78});}const width=Math.max(660,...[...pos.values()].map(p=>p.x+220)),height=Math.max(190,...[...pos.values()].map(p=>p.y+85));const root=svg('svg',{class:'graph',width,height,viewBox:`0 0 ${width} ${height}`,role:'img','aria-label':'静态调用关系图'});const defs=svg('defs'),marker=svg('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(svg('polyline',{points:'1,1 9,5 1,9',fill:'none',stroke:'#a9bec8'}));defs.append(marker);root.append(defs);for(const edge of data.edges){const a=pos.get(edge.source),b=pos.get(edge.target);if(!a||!b)continue;root.append(svg('path',{d:`M ${a.x+205} ${a.y+25} C ${a.x+225} ${a.y+25}, ${b.x-25} ${b.y+25}, ${b.x} ${b.y+25}`,'marker-end':'url(#arrow)'}));}for(const node of nodes){const p=pos.get(node.id),g=svg('g',{class:'graph-node'+(roots.has(node.id)?' node-root':''),transform:`translate(${p.x},${p.y})`,tabindex:0,role:'button','aria-label':node.label});g.append(svg('rect',{width:205,height:50,rx:7}));const label=node.label.split('.').slice(-2).join('.');const title=svg('title');title.textContent=node.label;const t=svg('text',{x:12,y:20});t.textContent=label.length>26?label.slice(0,25)+'…':label;const sub=svg('text',{x:12,y:37,class:'graph-sub'});sub.textContent=`${node.repo_id.toUpperCase()} · ${node.kind}`;g.append(title,t,sub);const open=()=>node.evidence?.web_evidence_id?showEvidence(node.evidence.web_evidence_id):toast('此节点没有可预览证据');g.addEventListener('click',open);g.addEventListener('keydown',e=>{if(e.key==='Enter')open();});root.append(g);}add(wrap,root);if(nodes.length<data.nodes.length)add(wrap,el('p','hint',`图中显示前 ${nodes.length} 个节点，下方列表保留全部 ${data.nodes.length} 个节点。`));return wrap;}
function renderAnalysis(){const main=$('main');add(main,heading('REQUIREMENT WORKFLOW','需求分析','明确目标与验收条件，将知识检索、代码追踪和证据核验串成一份报告。'));const layout=el('div','analysis-layout'),p=panel('定义分析范围','不自动补写用户决策'),form=el('form');const goal=field('需求目标 *','goal',state.pendingGoal||'','textarea','描述你要分析的需求或接口…');state.pendingGoal=null;goal.input.required=true;add(form,goal.wrap);add(form,button('使用 01100121 基准分析样例','ghost',()=>{goal.input.value='分析 01100121 贷款产品查询的当前契约、静态调用链与影响范围';form.elements.non_goals.value='不修改业务代码，不连接业务服务';form.elements.acceptance_criteria.value='定位当前接口契约、静态链路和对应证据';state.drafts.analysis=Object.fromEntries(new FormData(form));}));const ng=field('非目标','non_goals','','textarea','不在本次分析范围内的内容，每行一项'),ac=field('验收条件','acceptance_criteria','','textarea','希望报告回答哪些问题，每行一项');add(form,el('div','section-space'),ng.wrap,ac.wrap);const advanced=el('details');add(advanced,el('summary','','更多需求字段'));for(const[label,name]of [['业务对象','business_objects'],['接口号','interface_ids'],['补充检索词','terms'],['约束','constraints'],['待确认事项','open_questions'],['用户已做出的决策','user_decisions']])add(advanced,field(label,name,'','textarea','每行一项').wrap);add(form,advanced);const backend=selectField('分析模式','backend',[['template','确定性模板 · 不调用模型'],['mock','离线 Mock · 验证辅助流程'],['zhipu','智谱 · 模型辅助']]);add(form,backend.wrap);const modelOptions=el('div','model-options hidden'),model=field('模型名称','model',state.status.default_model),context=selectField('发送给模型的内容','context',[['requirement-only','仅本次需求字段'],['verified-facts','需求 + 最多 40 条已验证事实']]);add(modelOptions,model.wrap,context.wrap,el('p','hint','不会发送完整源码或本机路径。仅将允许出域的内容发送给智谱；密钥从启动服务的环境变量读取。'),el('p','hint',state.status.model_key_available?'服务进程已配置模型密钥。':'服务进程未配置密钥；智谱调用将回退模板。'));backend.input.addEventListener('change',()=>modelOptions.classList.toggle('hidden',backend.input.value==='template'));add(form,modelOptions);const submit=el('button','primary section-space','开始分析  →');add(form,submit,el('p','hint','分析结果仅保留在当前服务会话，可完成后导出保存。'));form.addEventListener('submit',e=>{e.preventDefault();state.drafts.analysis=Object.fromEntries(new FormData(form));run('analyze-requirement',state.drafts.analysis);});add(p.body,form);add(layout,p.box);const output=el('div'),job=state.results.analysis;if(job){renderReport(output,job);}else{add(output,add(el('div','analysis-info'),el('span','eyebrow','FROM REQUIREMENT TO EVIDENCE'),el('h3','','一份可核验的分析报告'),el('p','','报告会按事实来源拆分结论，保留版本、冲突与覆盖缺口，让你知道哪些已经确认，哪些仍需补充。'),pipeline()));const sections=panel('报告包含什么','10 步确定性工作流');for(const [title,desc]of [['知识事实与当前代码','区分知识记载、静态代码、历史与用户决策'],['影响与契约冲突','展示潜在依赖、字段冲突与对齐结果'],['覆盖范围与待确认问题','预算截断、未解析关系和证据不足均显式保留'],['可以打开的证据','从每条事实直接查看源码或知识片段']])add(sections.body,add(el('div','list-row'),add(el('div','row-text'),el('strong','',title),el('small','',desc))));add(output,el('div','section-space'),sections.box);}add(layout,output);add(main,layout);}
function renderReport(parent,job){const data=job.result,labels={complete:'分析完成',partial:'部分分析 · 仍有待确认项',blocked:'证据门禁阻断'};add(parent,add(el('div','report-banner '+data.status),add(el('div'),el('h3','',labels[data.status]||data.status),el('p','',`${data.verification.fact_count} 条事实 · ${data.verification.ok?'事实校验通过':'校验未通过'} · ${data.mode}`)),badge(data.publishable?'可复核':'需处理',data.publishable?'good':'bad')),downloads(job));if(data.coverage.blockers.length)add(parent,el('div','notice',data.coverage.blockers.join('\n')));for(const[category,title]of [['knowledge_facts','知识事实'],['code_facts','当前代码事实'],['historical_facts','历史事实（知识记载）'],['inferences','模型推断 · 待复核'],['recommendations','建议 · 待复核'],['open_questions','待确认问题']]){const claims=data.claims.filter(c=>c.category===category);if(!claims.length)continue;const p=panel(title,`${claims.length} 项`);for(const claim of claims){const f=el('div','fact');add(f,el('p','',claim.text));if(claim.source==='model')add(f,el('p','hint',`${claim.confidence_reason}；反证/限制：${claim.countercondition}`));add(f,add(el('div','fact-meta'),claim.evidence_ids.map(id=>evidenceButton(data.evidence_ledger[id]))));add(p.body,f);}add(parent,p.box);}if(data.user_decisions?.length){const p=panel('用户决策','输入原文');add(p.body,el('p','subtle',data.user_decisions.join('\n')));add(parent,p.box);}for(const[key,title]of [['coverage','覆盖范围'],['conflicts','冲突'],['unresolved','未解析关系'],['snapshots','四仓快照'],['model_assistance','模型辅助与审计']])if(data[key]){const p=panel(title,'');add(p.body,rawDetails(data[key]));add(parent,p.box);}}
function renderConflicts(){const main=$('main');add(main,heading('CONTRACT CONSISTENCY','契约与冲突','对照知识字段、历史记载与固定代码契约，识别需要处理的差异。'));const form=el('form','search-box'),input=el('input');input.value='01100121';input.placeholder='输入八位接口号，留空检查全部';input.setAttribute('aria-label','接口号');add(form,input,el('button','primary','检测冲突'));form.addEventListener('submit',e=>{e.preventDefault();run('detect-conflicts',{query:input.value});});add(main,form,el('div','notice','找不到精确代码端点时标记为待解析，不直接宣称代码漂移。历史差异与当前阻断冲突分别处理。'));const job=state.results.conflicts;if(!job)return add(main,empty('核对知识与代码契约','输入接口号开始检查，或留空检查当前知识索引中的全部结构化接口字段。','⇄'));const d=job.result;add(main,add(el('div','report-banner '+(d.ok?'':'blocked')),add(el('div'),el('h3','',d.ok?'未发现当前阻断冲突':'存在需要处理的阻断冲突'),el('p','',`${d.summary.claims} 条字段事实 · ${d.summary.blocking_conflicts} 个阻断冲突`)),downloads(job)));for(const conflict of d.conflicts)add(main,el('div','notice',`${conflict.field_name} · ${conflict.conflict_kind}：${conflict.description}`));const p=panel('知识字段事实','保留文档状态与作用域');for(const claim of d.claims)add(p.body,add(el('div','fact'),add(el('div','result-title'),badge(claim.assertion_scope),el('span','',`${claim.field_name} = ${claim.normalized_value}`)),el('p','hint',`${claim.interface_id} · ${claim.title} · ${claim.status}`),evidenceButton(claim)||evidenceButton(claim.evidence)));if(!d.claims.length)add(p.body,el('p','subtle','当前知识快照内未找到可抽取的字段事实。'));add(main,p.box);const alignment=panel('代码端点对齐',`${d.code_alignment.length} 项`);for(const a of d.code_alignment){const f=el('div','fact');add(f,add(el('div','result-title'),badge(a.status==='aligned'?'精确对齐':'待解析',a.status==='aligned'?'good':'warn'),el('span','',`${a.document_contract.http_method} ${a.document_contract.route}`)));for(const evidence of a.code_evidence)add(f,evidenceButton(evidence));add(alignment.body,f);}add(main,alignment.box);}
function renderRepositories(){const main=$('main');add(main,heading('REPOSITORIES & INDEX','仓库与索引','检查固定版本与本机工作树，按需刷新派生索引。'));const controls=el('div','repo-controls');for(const[action,label]of [['snapshots','检查四仓快照'],['index-code','更新代码索引'],['index-docs','更新知识索引']])add(controls,button(label,action==='snapshots'?'primary':'secondary',()=>run(action)));add(controls,button('刷新状态','secondary',async()=>{try{await refresh();render();}catch(e){toast(e.message);}}));add(main,controls,el('div','notice','索引更新仅写入本项目 var/。业务仓库的源码、现有修改和知识库本机元数据保持不变。'));const p=panel('索引概况',`${state.status.counts.files.toLocaleString()} 个代码文件`);p.body.remove();add(p.box,repositoryTable());add(main,p.box);const job=state.results.repositories;if(job){const r=panel(actionNames[job.action]+'结果',job.result.ok===false?'需要核对':'执行完成');add(r.body,downloads(job));if(job.action==='snapshots')for(const snap of job.result.snapshots){const item=el('div','fact');add(item,add(el('div','result-title'),badge(snap.ok?'基线匹配':'存在差异',snap.ok?'good':'warn'),el('span','',snap.repo_id.toUpperCase())),el('p','mono',`${snap.branch} / ${snap.head}`),el('p','hint',`本机修改 ${snap.changes.length} 项 · 未登记修改 ${snap.unexpected_changes.length} 项`));if(!snap.ok)add(item,rawDetails(snap));add(r.body,item);}else add(r.body,rawDetails(job.result));add(main,r.box);}else add(main,el('div','section-space'),empty('索引状态不等于快照已检查','点击“检查四仓快照”核对 HEAD、分支、远程基线和现有工作树修改。','▤'));}
function render(){state.page=Object.hasOwn(pages,location.hash.slice(1))?location.hash.slice(1):'overview';$('page-label').textContent=pages[state.page];document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===state.page);if(a.dataset.page===state.page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('main').replaceChildren();if(!state.status)return add($('main'),empty('正在连接本地服务','请稍候…'));({overview:renderOverview,analysis:renderAnalysis,search:renderSearch,trace:renderTrace,conflicts:renderConflicts,repositories:renderRepositories})[state.page]();restoreDraft();}
$('close-evidence').addEventListener('click',()=>$('evidence-dialog').close());window.addEventListener('hashchange',render);
(async()=>{try{const r=await fetch('/api/session',{headers:{'X-BankDev-Web':'1'}});if(!r.ok)throw new Error('无法创建本机会话，请使用服务启动时显示的 127.0.0.1 地址。');state.token=(await r.json()).token;await refresh();render();}catch(e){$('connection-label').textContent='连接失败';$('main').replaceChildren(empty('暂时无法连接工作台',e.message));}})();

function restoreDraft(){
  const form=$('main').querySelector('form'),draft=state.drafts[state.page];
  if(!form||!draft)return;
  for(const [name,value] of Object.entries(draft)){const input=form.elements.namedItem(name);if(input)input.value=value;}
  const options=$('main').querySelector('.model-options');
  if(options)options.classList.toggle('hidden',form.elements.backend.value==='template');
}
for(const type of ['input','change'])document.addEventListener(type,event=>{
  const form=event.target.closest('form');
  if(form)state.drafts[state.page]=Object.fromEntries(new FormData(form));
});
